### ISSUE TITLE
Question: Schema extension + composition

### ISSUE THREAD

**Issue by andrewosh** [beakerbrowser/libfritter#5]
Hey Beaker(er?)s,

I'm curious what the current recommendation is for creating schema extensions that would be compatible with existing Fritter clients. More specifically, I'd like to add an optional `type` field + metadata to some Freets while keeping all other fields intact, such that existing clients render some placeholder text (i.e. "To view this message, use viewer X," ala SSB) if they lack the ability to display/handle the complete message.

It looks like right now message validation is manual, and doesn't actually use any of the JSON schemas in `schemas/`, which means that schema duplication is really only be an aesthetic problem, since validators can be easily composed. That right?

I know you've given this tons of thought (w.r.t. app intents and JSON-LZ), and I know that additional WebDB work is tabled until the hyperdb API lands -- in the meantime, what's ideal? Also, any known examples that currently do this? 

Thanks!

**Comment by pfrazee** [comment]
Heyo @andrewosh.

Yeah I think you have two choices here. You can:

 1. Intentionally break the existing schema validation (ie no `text` field). This would cause other clients to ignore the new post-types, but allow you to still weave them into the feeds of compliant clients.
 2. Treat the existing schema like an envelope. In this case, you would put the "To view this message..." bit in the `text` field, and then add attributes containing your new data. This would cause other clients to render the new post-types as posts, containing whatever text you have in the `text` field.

That's basically up to you. I'd suggest you only go with 2 if you're sure it won't look spammy.

RE the json-schemas, yeah I was using those and then I noticed the json-schema library I was using added a ton of kBs to the bundle so I ditched it.

**Comment by andrewosh** [comment]
K great -- I didn't know that validation errors would cause clients to ignore the data instead of explicitly erroring. That sounds like the best approach for my use-case!
